typography_spectrum: 0.6019235758576542
color:
  brandStrength: 0.6955714910291135
  lightness: 0.0518331762868911
  saturation: 0.4851983767002821
  rhythmicContrast: 0.8766619160305709
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.7125158275011927
name: webtrzymanie
navigation:
  - name: Tumblr
    url: 'https://webtrzymanie.tumblr.com/'
    type: external
title: WebTrzymanie
description: Utrzymanie stron internetowych
